export const REQUEST_RIDE = 'REQUEST_RIDE';

export const REMOVE_REQUEST = 'REMOVE_REQUEST';

export const ADD_ARTICLE = 'ADD_ARTICLE';
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE';


export const REQUEST_LOCATION_PENDING = 'REQUEST_LOCATION_PENDING';
export const REQUEST_LOCATION_SUCCESS = 'REQUEST_LOCATION_SUCCESS';
export const REQUEST_LOCATION_FAILED = 'REQUEST_LOCATION_FAILED';